% Solve an Autoregression Time-Series Problem with a NAR Neural Network
% Script generated by NTSTOOL
% Created Mon Aug 01 09:39:01 EDT 2011
%
% This script assumes this variable is defined:
%
%   SPY - feedback time series.


 

clear;
load SSnet net;
N=net.numInputDelays-1; %the smallest number of rows in all the historical data

 
%%%input data of GSPC
SSVOLUM=0.00000001*csvread('C:\Company\historical\000001.SS.csv',1,5,[1,5,N+1,5]);
SSVOLUM =flipud(SSVOLUM);
SS=0.01*csvread('C:\Company\historical\000001.SS.csv',1,1,[1,1,N+1,4]);
SS=flipud(SS); 

 

inputSeries = tonndata(SSVOLUM,false,false);
targetSeries = tonndata(SS,false,false);

 [inputs,inputStates,layerStates,targets] = preparets(net,inputSeries,{},targetSeries);

 
nets = removedelay(net);
nets.name = [net.name ' - Predict One Step Ahead'];
 
[xs,xis,ais,ts] = preparets(nets,inputSeries,{},targetSeries);
ys = nets(xs,xis,ais);

 

file=fopen('C:\\Company\\historical\\000001.SS.csv');
xiao=textscan(file, '%s', 'delimiter', ',');
xiao=[xiao{:}];
x=xiao(8);

y=textscan([x{:}], '%d', 'delimiter', '-');
z=[y{:}];
z=double(z);
n=datenum(z(1),z(2),z(3));
[zhouji,libaiji]=weekday(n);

A=100*ys{:,N-14};
%B=double(csvread('C:\\Company\\result1D.csv', 1,0,[1,0,1,3])); 
C=[zhouji-1,A'];
csvwrite('C:\\Company\\result1DS.csv', C);
f = ftp('ftp.ipage.com','aatsyscom','DongFeng09$$');
try
delete(f,'result1DS.csv');
catch exception
end
mput(f,'C:\\Company\\result1DS.csv');
 close(f);
clear;
 
 
  