% Solve an Autoregression Time-Series Problem with a NAR Neural Network
% Script generated by NTSTOOL
% Created Mon Aug 01 09:39:01 EDT 2011
%
% This script assumes this variable is defined:
%
%   SPY - feedback time series.


 

clear;
N=2960; %the smallest number of rows in all the historical data

 
%%%input data of GSPC
SSVOLUM=0.00000001*csvread('C:\Company\historical\000001.SS.csv',1,5,[1,5,N+1,5]);
SSVOLUM =flipud(SSVOLUM);
SS=0.01*csvread('C:\Company\historical\000001.SS.csv',1,1,[1,1,N+1,4]);
SS=flipud(SS); 

 

inputSeries = tonndata(SSVOLUM,false,false);
targetSeries = tonndata(SS,false,false);

inputDelays = 1:16;
feedbackDelays = 1:16;
hiddenLayerSize = 32;
while(true)
net = narxnet(inputDelays,feedbackDelays,hiddenLayerSize);
 

% Prepare the Data for Training and Simulation
% The function PREPARETS prepares timeseries data for a particular network,
% shifting time by the minimum amount to fill input states and layer states.
% Using PREPARETS allows you to keep your original time series data unchanged, while
% easily customizing it for networks with differing numbers of delays, with
% open loop or closed loop feedback modes.
[inputs,inputStates,layerStates,targets] = preparets(net,inputSeries,{},targetSeries);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
%performance=5;

 
[net,tr] = train(net,inputs,targets,inputStates,layerStates);

% Test the Network
outputs = net(inputs,inputStates,layerStates);
errors = gsubtract(targets,outputs);
net.performFcn='mae';
performance = perform(net,targets,outputs);

 
  SSperformance=100*performance
nets = removedelay(net);
nets.name = [net.name ' - Predict One Step Ahead'];
 
[xs,xis,ais,ts] = preparets(nets,inputSeries,{},targetSeries);
ys = nets(xs,xis,ais);
A=100*ys{:,N-14};
if(A(2)>=A(1) && A(2)>=A(3) && A(2)>=A(4) && A(3)<=A(1) && A(3)<=A(4))
    break;
end
clear net;
clear nets;
end

 

file=fopen('C:\\Company\\historical\\000001.SS.csv');
xiao=textscan(file, '%s', 'delimiter', ',');
xiao=[xiao{:}];
x=xiao(8);

y=textscan([x{:}], '%d', 'delimiter', '-');
z=[y{:}];
z=double(z);
n=datenum(z(1),z(2),z(3));
[zhouji,libaiji]=weekday(n);

 
%B=double(csvread('C:\\Company\\result1D.csv', 1,0,[1,0,1,3])); 
C=[zhouji-1,A',SSperformance];
csvwrite('C:\\Company\\result1DS.csv', C);
f = ftp('ftp.ipage.com','aatsyscom','DongFeng09$$');
try
delete(f,'result1DS.csv');
catch exception
end
mput(f,'C:\\Company\\result1DS.csv');
 close(f);
save SSnet net;
 
 
  