% Solve an Autoregression Time-Series Problem with a NAR Neural Network
% Script generated by NTSTOOL
% Created Mon Aug 01 09:39:01 EDT 2011
%
% This script assumes this variable is defined:
%
%   SPY - feedback time series.


 

clear;
file=urlread('http://finance.yahoo.com/q?s=000001.SS');
[mat idx] = regexp(file, '>Open:</th><td class="yfnc_tabledata1">(\d\,\d\d\d\.\d\d)</td>','tokens');
OPEN=0.01*str2double(mat{:}); 
N=2960; %the smallest number of rows in all the historical data

 
 
%%%input data of GSPC
 
SSVOLUM=0.00000001*csvread('C:\Company\historical data\000001.SS.csv',1,5,[1,5,N+1,5]);
SSVOLUM =flipud(SSVOLUM);
SS=0.01*csvread('C:\Company\historical data\000001.SS.csv',1,1,[1,1,N+1,4]);
SS=flipud(SS);
SSOPEN=SS(2:end,1:1);
SSOPEN=[SSOPEN',OPEN]';
 
ALLOVERVOLUM=[SSOPEN,SSVOLUM];
mubiao=SS(1:end,2:4);
inputSeries = tonndata(ALLOVERVOLUM,false,false);
targetSeries = tonndata(mubiao,false,false);

inputDelays = 1:16;
feedbackDelays = 1:16;
hiddenLayerSize = 32;
net = narxnet(inputDelays,feedbackDelays,hiddenLayerSize);
 

% Prepare the Data for Training and Simulation
% The function PREPARETS prepares timeseries data for a particular network,
% shifting time by the minimum amount to fill input states and layer states.
% Using PREPARETS allows you to keep your original time series data unchanged, while
% easily customizing it for networks with differing numbers of delays, with
% open loop or closed loop feedback modes.
[inputs,inputStates,layerStates,targets] = preparets(net,inputSeries,{},targetSeries);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,inputs,targets,inputStates,layerStates);

% Test the Network
outputs = net(inputs,inputStates,layerStates);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs)

 
nets = removedelay(net);
nets.name = [net.name ' - Predict One Step Ahead'];
 
[xs,xis,ais,ts] = preparets(nets,inputSeries,{},targetSeries);
ys = nets(xs,xis,ais);
 

A=100*ys{:,N-14};
A=[100*OPEN,A']';
B=csvread('C:\Company\result.csv', 0,0,[0,0,0,3]); 
C=[B',A]';
csvwrite('C:\Company\result.csv', C);
f = ftp('ftp.ipage.com','aatsyscom','DongFeng09$$');
delete(f,'result.csv');
mput(f,'C:\Company\result.csv');
 close(f);
