% Solve an Autoregression Time-Series Problem with a NAR Neural Network
% Script generated by NTSTOOL
% Created Mon Aug 01 09:39:01 EDT 2011
%
% This script assumes this variable is defined:
%
%   SPY - feedback time series.

clear;

file=urlread('http://finance.yahoo.com/q?s=SPY');
[mat idx] = regexp(file, '>Open:</th><td class="yfnc_tabledata1">(\d\d\d\.\d\d)</td>','tokens');
OPEN=str2double(mat{:}); 

N=4650; %the smallest number of rows in all the historical data

VIXVOLUM=csvread('C:\Program Files (x86)\YLoader\data\^VIX.csv',0,5);
[rows,columns]=size(VIXVOLUM);
VIX=csvread('C:\Program Files (x86)\YLoader\data\^VIX.csv',rows-N-1,1, [rows-N-1,1,rows-1,4]);
 
%%%input data of GSPC
SPYVOLUM=csvread('C:\Program Files (x86)\YLoader\data\SPY.csv',0,5);
[rows,columns]=size(SPYVOLUM);
SPY=csvread('C:\Program Files (x86)\YLoader\data\SPY.csv',rows-N-1,2, [rows-N-1,2,rows-1,4]);
SPYOPEN=csvread('C:\Program Files (x86)\YLoader\data\SPY.csv',rows-N,1, [rows-N,1,rows-1,1]);
SPYOPEN=[SPYOPEN',OPEN]';

SPYVOLUM=0.0000001*SPYVOLUM((rows-N):rows,1:1);
ALLOVERVOLUM=[SPYOPEN,SPYVOLUM,VIX];
inputSeries = tonndata(ALLOVERVOLUM,false,false);
targetSeries = tonndata(SPY,false,false);

% Create a Nonlinear Autoregressive Network with External Input
inputDelays = 1:8;
feedbackDelays = 1:8;
hiddenLayerSize = 16;

net = narxnet(inputDelays,feedbackDelays,hiddenLayerSize);
 

% Prepare the Data for Training and Simulation
% The function PREPARETS prepares timeseries data for a particular network,
% shifting time by the minimum amount to fill input states and layer states.
% Using PREPARETS allows you to keep your original time series data unchanged, while
% easily customizing it for networks with differing numbers of delays, with
% open loop or closed loop feedback modes.
[inputs,inputStates,layerStates,targets] = preparets(net,inputSeries,{},targetSeries);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,inputs,targets,inputStates,layerStates);

% Test the Network
outputs = net(inputs,inputStates,layerStates);
errors = gsubtract(targets,outputs);
%performance = perform(net,targets,outputs)

 
nets = removedelay(net);
nets.name = [net.name ' - Predict One Step Ahead'];
 
[xs,xis,ais,ts] = preparets(nets,inputSeries,{},targetSeries);
ys = nets(xs,xis,ais);
 

A=100*ys{:,N-6}';
csvwrite('C:\Company\result.csv', A(1:3),0,1);
f = ftp('ftp.ipage.com','aatsyscom','DongFeng09$$');
delete(f,'result.csv');
mput(f,'C:\Company\result.csv');
 close(f);
